modLoader="javafml"
loaderVersion="[2,)"  # 1.21.1 通常对应 loader 版本 2 或以上
license="MIT"         # 替换你的协议

[[mods]]
modId="mkgmod"           # 必须手动写死
version="1.0.0"          # 你的版本号
displayName="MKG Mod"    # 你的模组名字
description='''
MKG Mod for Minecraft 1.21.1.
'''

# 依赖 NeoForge
[[dependencies.mkgmod]]        # 注意这里直接写 .mkgmod
modId="neoforge"
type="required"
versionRange="[21,)"       # 1.21.1 对应的 NeoForge 主版本是 21
ordering="NONE"
side="BOTH"

# 依赖 TerraBlender
#[[dependencies.mkgmod]]        # 同样，这里也要改
#modId = "terrablender"
#type = "required"
#versionRange = "[4.1.0.1,)"
#ordering = "BEFORE"
#side = "BOTH"
